[package]
name = "terramine"
version = "0.0.2"
edition = "2021"

[dependencies]
glium = "0.32.1"
image = "0.24.3"
directx_math = "0.2.2"
imgui = "0.10.0"
imgui-winit-support = "0.10.0"
winapi = "0.3.9"
profiler = { path = "../profiler" }
crossbeam = "0.8.1"
tokio = { version = "1.27.0", features = ["full"] }
tokio-stream = "0.1.12"
math_linear = { version = "0.1.0", path = "../math_linear", features = ["byte_muck"]}
thiserror = "1.0.40"
rayon = "1.7.0"
winit = "0.27.5"
derive-deref-rs = "0.1.1"
lazy_static = "1.4.0"
portable-atomic = { version = "1.2.0", features = ["float"] }
huffman-compress = "0.6.1"
bit-vec = "0.6.3"
array-init = "2.1.0"
cpython = { version = "0.7.1", features = ["extension-module"] }
smallvec = { version = "1.10.0", features = ["const_generics"] }
parse-display = "0.8.0"
noise = "0.8.2"
futures = "0.3.28"
user-error = "1.2.8"
itertools = "0.10.5"
atomic = "0.5.1"
ordered-float = "3.6.0"
rand = "0.8.5"
wgpu = "0.15.1"
imgui-wgpu = "0.22.0"
static_assertions = "1.1.0"
env_logger = "0.10.0"
log = "0.4.17"
pollster = "0.3.0"
bytemuck = { version = "1.13.1", features = ["derive"] }
type-uuid = "0.1.2"
smart-default = "0.6.0"
encase = "0.5.0"
bevy_ecs = "0.10.1"

[dependencies.spin]
version = "0.9.8"
features = [
    "mutex",
    "spin_mutex",
    "ticket_mutex",
    "rwlock",
    "once",
    "lazy",
    "barrier",
    "lock_api"
]

[target.'cfg(windows)'.build-dependencies]
winres = "0.1.12"

[features]
release = []
