[package]
name = "terramine"
version = "0.0.1"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glium = "0.30.1"
image = "*"
directx_math = "*"
imgui = "*"
imgui-glium-renderer = "*"
imgui-winit-support = "*"
winapi = "*"
profiler = { path = "../profiler" }
crossbeam = "0.8.1"
tokio = { version = "1.19.2", features = ["full"] }
tokio-stream = "0.1.9"

[features]
release = []