[package]
name = 'terramine'
version = '0.0.2'
edition = '2021'



[dependencies]
# Graphics
glium = '0.32.1'
wgpu = '0.15.1'
encase = '0.6.1'

# Platform
winit = '0.27.5'
image = '0.24.3'
winapi = '0.3.9'

# Gui
imgui = '0.10.0'
imgui-winit-support = '0.10.0'
imgui-wgpu = '0.22.0'

# Runtime
tokio = { version = '1.27.0', features = ['full'] }
tokio-stream = '0.1.12'
pollster = '0.3.0'
futures = '0.3.28'
crossbeam = '0.8.1'
rayon = '1.7.0'
portable-atomic = { version = '1.2.0', features = ['float'] }
atomic = '0.5.1'
cpython = { version = '0.7.1', features = ['extension-module'] }

# Macro utils
thiserror = '1.0.40'
derive-deref-rs = '0.1.1'
lazy_static = '1.4.0'
parse-display = '0.8.0'
user-error = '1.2.8'
type-uuid = '0.1.2'
smart-default = '0.7.1'
async-trait = '0.1.68'

# Math
directx_math = '0.2.2'
noise = '0.8.2'

# Utils
anyhow = '1.0.71'
huffman-compress = '0.6.1'
bit-vec = '0.6.3'
array-init = '2.1.0'
smallvec = { version = '1.10.0', features = ['const_generics', 'const_new'] }
itertools = '0.10.5'
ordered-float = '3.6.0'
rand = '0.8.5'
static_assertions = '1.1.0'
env_logger = '0.10.0'
log = '0.4.17'
bytemuck = { version = '1.13.1', features = ['derive'] }

# Terramine modules
terramine_ecs = { path = '../terramine_ecs', version = '0.1.0' }
math_linear = { version = '0.1.0', path = '../math_linear', features = ['byte_muck'] }
profiler = { path = '../profiler' }



[dependencies.spin]

version = '0.9.8'
features = [
    'mutex',
    'spin_mutex',
    'ticket_mutex',
    'rwlock',
    'once',
    'lazy',
    'barrier',
    'lock_api'
]



[target.'cfg(windows)'.build-dependencies]

winres = '0.1.12'



[features]
release = []
