use {
    std::{io::Cursor, fs, path::{Path, PathBuf}},
    glium::{
        uniforms::SamplerWrapFunction,
        texture::{RawImage2d, SrgbTexture2d, MipmapsOption},
        uniforms::{Sampler, MagnifySamplerFilter, MinifySamplerFilter},
    },
    glium as gl,
    math_linear::prelude::*,
};

/// Texture struct.
/// Contains texture stuff.
#[derive(Debug)]
pub struct Texture {
    pub path: PathBuf,
    pub opengl_texture: SrgbTexture2d,
    pub sizes: UInt2,
}

impl Texture {
    /// Loads texture from path.
    pub fn from_path(path: impl AsRef<Path>, display: &gl::Display) -> Result<Self, std::io::Error> {
        let path_buf = path.as_ref().to_owned();
        let image_bytes = fs::read(path)?;

        let image = image::load(Cursor::new(image_bytes), image::ImageFormat::Png)
            .expect("failed to load image")
            .to_rgba8();
        let image_size = image.dimensions();
        let image = RawImage2d::from_raw_rgba_reversed(&image.into_raw(), image_size);
        
        let texture = SrgbTexture2d::with_mipmaps(
            display,
            image,
            MipmapsOption::AutoGeneratedMipmapsMax(4)
        ).expect("failed to add mipmaps to texture");

        Ok(Self {
            path: path_buf,
            opengl_texture: texture,
            sizes: UInt2::from(image_size)
        })
    }

    /// Adds mips to texture uniform.
    pub fn with_mips(&self) -> Sampler<SrgbTexture2d> {
        Sampler::new(&self.opengl_texture)
            .magnify_filter(MagnifySamplerFilter::Nearest)
            .minify_filter(MinifySamplerFilter::NearestMipmapNearest)
            .wrap_function(SamplerWrapFunction::Clamp)
            .anisotropy(4)
    }
}